### PR TITLE
fix: remove extra ")" from the code

### PR DESCRIPTION
**Pull request by Pankaj-SinghR**
remove extra ")" from the file

### CODE REVIEW

**Comment by PankajSingh1010** [comment]
@Akankshabhasin pls review and merge

**Comment by Akankshabhasin** [comment]
Approved & Merged!
Thank you so much @PankajSingh1010 for contributing 😄

**Comment by PankajSingh1010** [comment]
Thank you @Akankshabhasin . I have also filed other 2 PR pls also review them

**Comment by Akankshabhasin** [comment]
Sure, will review it. 👍

**Pull request merged**
