### PR TITLE
Updated Async files - python

### PR DESCRIPTION
**Pull request by atom19-i**
- [ ] 🎉 Feature Enhancement
- [x] 🐛 Bug Fix
- [ ] 📖 Documentation Update
- [ ] ❇️ Other

In the async files python code snippet, there are multiple areas where a boolean is expected in the params eg. 'detectPhrases': True. 
As per #222 , added params=json.dumps(params) wherever necessary in python code for async files, which solves the issue.

Fixes issue #222

### CODE REVIEW

**Comment by atom19-i** [comment]
@Akankshabhasin the last commit merge is a mistake. i will undo it asap

**Comment by atom19-i** [comment]
@pema-s can you please give any update on this PR?

**Review by vaibhavpatil-symblai — APPROVED** [review]
LGTM

**Comment by Akankshabhasin** [comment]
Thanks a lot for contributing to Symbl.ai. 🙌 
Please fill out the [Contributor form](https://docs.google.com/forms/d/e/1FAIpQLScBQjwTWKpCziEiAfxO5gdw1UHngjIJwbKr1COBkE-G2ov8Vw/viewform) in case you missed it out.
We will be reaching out to the contributors for Developer Swags via email this week. 🎁

**Pull request merged**
