### PR TITLE
DC-149

### PR DESCRIPTION
**Pull request by amritesh-singh**
- [ ] 🎉 Feature Enhancement
- [ ] 🐛 Bug Fix
- [ ] 📖 Documentation Update
- [ ] ❇️ Other

### CODE REVIEW

**Comment by pema-s** [comment]
On hold because we need to verify if someone has reviewed this code.

**Comment by avoliva** [comment]
`symbl-node` is the old library. It should be `@symblai/symbl-js`

**Review by avoliva — DISMISSED** [review]
Change `symbl-node` to `@symblai/symbl-js`

**Review by pema-s — APPROVED** [review]
LGTM

**Review by pema-s — APPROVED** [review]
LGTM

**Pull request merged**
