### PR TITLE
Corrected Typos and Grammatical errors in 12 files

### PR DESCRIPTION
**Pull request by HVbajoria**
### PR Details
**Description of the change**:  I went through the documents and found some had grammatical and typing mistakes. I have corrected it in 12 files. The files were :
1. CODE_OF_CONDUCT.md
2. README.md
3. changelog.md
4. faq.md
5. getting-started-with-async-api.md
6. getting-started-with-streaming-api.md
7. getting-started-with-telephony-api.md
8. labs.md
9. sdk-intro.md
10. subscribe-api.md
11. symbl-under-10-mins.md
12. what-is-symbl.md

**Reason for the change**: The readme and the instructions file should have no grammatical and typing mistakes. 

If there are any changes required. Please do let me know.
Will be happy to learn and grow.
Happy HacktoberFest

### CODE REVIEW

**Comment by HVbajoria** [comment]
Thank you @Akankshabhasin

**Comment by HVbajoria** [comment]
@Akankshabhasin I had just one question will it be counted as 1 PR or 2 PR's as it had 12 files. 
Could you please guide me. 
Thank you

**Comment by Akankshabhasin** [comment]
Technically it will be counted as one PR. 
You can read more about the rules and processes under the hacktoberfest section in our Contributing.md file.

**Comment by HVbajoria** [comment]
Thank you

**Pull request merged**
